In [2]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=.5)
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])
#Ridge(alpha=0.5)

Ridge(alpha=0.5, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=None, solver='auto', tol=0.001)

In [3]:
reg.coef_

array([0.34545455, 0.34545455])

In [4]:
reg.intercept_

0.13636363636363638

In [5]:
import numpy as np
from sklearn import linear_model
reg = linear_model.RidgeCV(alphas=np.logspace(-6, 6, 13))
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

RidgeCV(alphas=array([1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01,
       1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06]),
        cv=None, fit_intercept=True, gcv_mode=None, normalize=False,
        scoring=None, store_cv_values=False)

In [6]:
reg.alpha_

0.01

In [8]:
from sklearn import linear_model 
reg = linear_model.Lasso(alpha=0.1)
reg.fit([[0, 0], [1, 1]], [0, 1])

Lasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [9]:
reg.predict([[1, 1]])

array([0.8])

--------------

In [10]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [11]:
x = np.array([5, 15, 25, 35, 45, 55]).reshape((-1, 1))
y = np.array([5, 20, 14, 32, 22, 38])

In [12]:
model = LinearRegression()

In [13]:
model.fit(x, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [14]:
model = LinearRegression().fit(x, y)

In [15]:
r_sq = model.score(x, y)
print('coefficient of determination:', r_sq)

coefficient of determination: 0.7158756137479542


In [16]:
print('intercept:', model.intercept_)

intercept: 5.633333333333329


In [17]:
print('slope:', model.coef_)

slope: [0.54]


In [18]:
new_model = LinearRegression().fit(x, y.reshape((-1, 1)))

In [19]:
print('intercept:', new_model.intercept_)

intercept: [5.63333333]


In [20]:
print('slope:', new_model.coef_)

slope: [[0.54]]


In [21]:
y_pred = model.predict(x)

In [22]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[ 8.33333333 13.73333333 19.13333333 24.53333333 29.93333333 35.33333333]


In [23]:
y_pred = model.intercept_ + model.coef_ * x

In [24]:
print('predicted response:', y_pred, sep='\n')

predicted response:
[[ 8.33333333]
 [13.73333333]
 [19.13333333]
 [24.53333333]
 [29.93333333]
 [35.33333333]]


In [25]:
x_new = np.arange(5).reshape((-1, 1))

In [26]:
print(x_new)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [27]:
y_new = model.predict(x_new)

In [28]:
print(y_new)

[5.63333333 6.17333333 6.71333333 7.25333333 7.79333333]
